autoserver/urls.py
from django.contrib import admin
from django.urls import path,include
from api.views import asset
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('server/',include('backend.urls')),
    path('admin/', admin.site.urls),
    path('asset/',asset)
]

backend/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.server, name='server'),
    path('back/', views.bakcserver, name='bakcserver'),
    path('<int:pk>/<str:type>', views.serverdetail, name='serverdetail'),
    path('cpu/<int:server_pk>', views.GetCpu, name='getcpu'),
    path('mem/<int:server_pk>', views.GetMem, name='getmem'),
    path('swap/<int:server_pk>', views.GetSwap, name='getswap'),
    #path('disk/<int:server_pk>', views.GetDisk, name='getdisk'),
    path('net/<int:server_pk>', views.GetNetInfo, name='getnet'),
]

respository/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class UserProfile(models.Model):
    username = models.CharField(u'姓名',max_length=32)
    password = models.CharField(u'密码',max_length=64)
    phone = models.CharField(u'手机',max_length=32)
    email = models.EmailField(u'姓名')

    class Meta:
        verbose_name_plural = '用户表'

    def __str__(self):
        return self.username


class Product(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = '业务系统'

    def __str__(self):
        return self.name

class Area(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = '地区表'

    def __str__(self):
        return self.name

class Server(models.Model):

    device_type_choices = (
        (1, '服务器'),
        (2, '交换机'),
        (3, '防火墙'),
    )

    device_status_choices = (
        (1, '在运'),
        (2, '退运'),
    )
    device_sync_choices = (
        (0, '未同步'),
        (1, '已同步'),
    )
    device_type_id = models.IntegerField('服务器类型',choices=device_type_choices,default=1)
    device_status_id = models.IntegerField('服务器状态', choices=device_status_choices, default=1)

    ipaddr = models.CharField('IP',max_length=128,unique=True)
    hostname = models.CharField('主机名',max_length=128,null=True,blank=True)
    os_platform = models.CharField('操作系统',max_length=32,null=True,blank=True)
    os_version = models.CharField('操作系统版本',max_length=128,null=True,blank=True)
    manufacturer = models.CharField('制造商',max_length=128,null=True,blank=True)
    model = models.CharField('型号',max_length=128,null=True,blank=True)
    sn = models.CharField('SN号',max_length=128,null=True,blank=True,db_index=True)

    area = models.ForeignKey('Area',verbose_name='地区',null=True,blank=True,on_delete=models.CASCADE)
    idc = models.CharField('机房',max_length=128,null=True,blank=True)
    cabinet = models.CharField('机柜位置',max_length=128,null=True,blank=True)

    cpu_count = models.IntegerField('CPU个数',null=True,blank=True)
    cpu_physical_count = models.IntegerField('CPU物理个数',null=True,blank=True)
    cpu_model = models.CharField('CPU型号',max_length=128,null=True,blank=True)
    mem_total = models.CharField('内存总量',max_length=50,null=True,blank=True)
    product = models.ForeignKey('Product',verbose_name='业务系统',on_delete=models.CASCADE)

    create_time = models.DateTimeField(auto_now_add=True,blank=True)

    tag = models.ManyToManyField('Tag',null=True,blank=True)

    is_sync = models.IntegerField('同步状态', choices=device_sync_choices, default=0)
    class Meta:
        verbose_name_plural = '服务器表'

    def __str__(self):
        return self.ipaddr


class Cpu(models.Model):
    server = models.ForeignKey('Server',related_name='cpu',on_delete=models.CASCADE)
    percent_avg = models.CharField('平均使用率',max_length=50)
    percent_per = models.CharField('每个CPU使用率',max_length=50)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'CPU信息表'

    def __str__(self):
        return self.percent_avg


class Mem(models.Model):
    server = models.ForeignKey('Server',related_name='mem' ,on_delete=models.CASCADE)
    mem_total = models.CharField('总内存',max_length=50,null=True,blank=True)
    used = models.CharField('已使用内存',max_length=50,null=True,blank=True)
    free = models.CharField('空闲内存',max_length=50,null=True,blank=True)
    percent = models.CharField('使用率',max_length=50,null=True,blank=True)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '内存信息表'

    def __str__(self):
        return self.mem_total

class Swap(models.Model):
    server = models.ForeignKey('Server',related_name='swap',verbose_name='服务器' ,on_delete=models.CASCADE)
    total = models.CharField('总Swap',max_length=50,null=True,blank=True)
    used = models.CharField('已使用Swap',max_length=50,null=True,blank=True)
    free = models.CharField('空闲Swap',max_length=50,null=True,blank=True)
    percent = models.CharField('使用率',max_length=50,null=True,blank=True)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '交换分区表'

    def __str__(self):
        return self.total


class Disk(models.Model):
    server = models.ForeignKey('Server', related_name='disk',on_delete=models.CASCADE)
    device = models.CharField('盘符',max_length=50)
    mountpoint = models.CharField('挂载点',max_length=50,null=True,blank=True)
    fstype = models.CharField('磁盘类型',max_length=50,null=True,blank=True)
    opts = models.CharField('磁盘权限',max_length=50,null=True,blank=True)
    total = models.CharField('容量',max_length=50,null=True,blank=True)

    class Meta:
        verbose_name_plural = '磁盘表'

    def __str__(self):
        return '%s-%s' % (self.server.ipaddr,self.device)

class DiskDetail(models.Model):
    disk = models.ForeignKey('Disk', on_delete=models.CASCADE)
    total = models.CharField('总容量',max_length=50,null=True,blank=True)
    used = models.CharField('已使用容量',max_length=50,null=True,blank=True)
    free = models.CharField('空闲容量',max_length=50,null=True,blank=True)
    percent = models.CharField('使用率',max_length=50,null=True,blank=True)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '磁盘信息表'

    def __str__(self):
        return '%s-%s' % (self.disk.server.ipaddr,self.disk.device)

class Net(models.Model):
    server = models.ForeignKey('Server',related_name='net',on_delete=models.CASCADE)
    name = models.CharField('网卡名称',max_length=50,null=True,blank=True)
    family = models.CharField('类型',max_length=50,null=True,blank=True)
    address = models.CharField('IP',max_length=50,null=True,blank=True)
    netmask = models.CharField('子关掩码',max_length=50,null=True,blank=True)
    broadcast = models.CharField('广播地址',max_length=50,null=True,blank=True)
    bytes_sent = models.CharField('已发送字节',max_length=50,default=0)
    bytes_recv = models.CharField('已接收字节',max_length=50,default=0)
    packets_sent = models.CharField('已发送包',max_length=50,default=0)
    packets_recv = models.CharField('已接收包',max_length=50,default=0)

    class Meta:
        verbose_name_plural = '网卡表'

    def __str__(self):
        return self.name

class ErrorLog(models.Model):
    title = models.CharField(max_length=32)
    content = models.TextField()
    server = models.ForeignKey('Server',related_name='el',null=True,blank=True, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '错误日志表'

    def __str__(self):
        return self.title



class ChangeLog(models.Model):
    content = models.TextField(null=True)
    server = models.ForeignKey('Server', related_name='cl',verbose_name='服务器',on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = '资产变更表'

    def __str__(self):
        return '%s-%s' % (self.server.ipaddr,self.server.hostname)


class Tag(models.Model):
    name = models.CharField('标签',max_length=32,unique=True)

    class Meta:
        verbose_name_plural = '标签表'

    def __str__(self):
        return self.name

templates/back_server.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block content %}
    <div class="content-box-large">
        <div class="panel-heading">
            <div class="panel-title">退运服务器</div>
        </div>
        <div class="panel-body">
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
                <thead>
                    <tr>
                        <th>IP</th>
                        <th>主机名</th>
                        <th>操作系统</th>
                        <th>操作系统版本</th>
                        <th>服务器类型</th>
                        <th>服务器状态</th>
                        <th>是否已同步</th>
                    </tr>
                </thead>
                <tbody>

                    {% for server in servers %}
                        <tr class="odd gradeX">
                            <td><a href="{% url 'serverdetail' server.pk 'return'  %}">{{ server.ipaddr }}</a></td>
                            <td>{{ server.hostname }}</td>
                            <td>{{ server.os_platform }}</td>
                            <td class="center">{{ server.os_version }}</td>
                            <td class="center">{{ server.get_device_type_id_display }}</td>
                            <td class="center">{{ server.get_device_status_id_display }}</td>
                            <td class="center">{{ server.get_is_sync_display }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'vendors/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendors/datatables/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'js/tables.js' %}"></script>
{% endblock %}

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>资产管理系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- styles -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <script src="{% static 'js/highcharts.js' %}"></script>
{#    <script src="{% static 'js/exporting.js' %}"></script>#}
    <script src="{% static 'js/highcharts-zh_CN.js' %}"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="header">
	     <div class="container">
	        <div class="row">
	           <div class="col-md-5">
	              <!-- Logo -->
	              <div class="logo">
	                 <h1><a href="index.html">资产管理系统</a></h1>
	              </div>
	           </div>
	           <div class="col-md-5">
	              <div class="row">
	                <div class="col-lg-12">
	                  <div class="input-group form">
	                  </div>
	                </div>
	              </div>
	           </div>
	           <div class="col-md-2">
	              <div class="navbar navbar-inverse" role="banner">
	                  <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
	                  </nav>
	              </div>
	           </div>
	        </div>
	     </div>
	</div>
    <div class="page-content">
    	<div class="row">
            <div class="col-md-2">
                <div class="sidebar content-box" style="display: block;">
                    <ul class="nav">
                    <!-- Main menu -->
                        <li class="current"><a href="{% url 'index' %}"><i class="glyphicon glyphicon-home"></i>首页</a></li>
                        <li><a href="{% url 'server' %}"><i class="glyphicon glyphicon-list"></i>在运服务器</a></li>
                        <li><a href="{% url 'bakcserver' %}"><i class="glyphicon glyphicon-list"></i> 退运服务器</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10">
                <div class="content-box-large">
                    <div class="panel-body">
                        <div class="row">
                            {% block content %}
                                <div id="container" style="min-width:400px;height:400px"></div>
                                <script>
                                    // Build the chart
                                    Highcharts.chart('container', {
                                            chart: {
                                                    plotBackgroundColor: null,
                                                    plotBorderWidth: null,
                                                    plotShadow: false,
                                                    type: 'pie'
                                            },
                                            title: {
                                                    text: '服务器'
                                            },
                                            tooltip: {
                                                    pointFormat: '{series.name}: <b>{point.y}</b>'
                                            },
                                            plotOptions: {
                                                    pie: {
                                                            allowPointSelect: true,
                                                            cursor: 'pointer',
                                                            dataLabels: {
                                                                    enabled: false
                                                            },
                                                            showInLegend: true
                                                    }
                                            },
                                            credits:{
                                                enabled: false // 禁用版权信息
                                            },
                                            series: [{
                                                    name: '数量',
                                                    colorByPoint: true,
                                                    data: [
                                                        {% for server in server_list %}
                                                            {
                                                            name: '{{ server.os_platform }}',
                                                            y: {{ server.platformNum }}
                                                    },
                                                        {% endfor %}
                                                        ]
                                            }]
                                    });
                                </script>
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
		</div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>

</body>
</html>

templates/server.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block content %}
    <div class="content-box-large">
        <div class="panel-heading">
            <div class="panel-title">服务器列表</div>
        </div>
        <div class="panel-body">
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
                <thead>
                    <tr>
                        <th>IP</th>
                        <th>主机名</th>
                        <th>操作系统</th>
                        <th>操作系统版本</th>
                        <th>服务器类型</th>
                        <th>服务器状态</th>
                        <th>是否已同步</th>
                    </tr>
                </thead>
                <tbody>

                    {% for server in servers %}
                        <tr class="odd gradeX">
                            <td><a href="{% url 'serverdetail' server.pk %}">{{ server.ipaddr }}</a></td>
                            <td>{{ server.hostname }}</td>
                            <td>{{ server.os_platform }}</td>
                            <td class="center">{{ server.os_version }}</td>
                            <td class="center">{{ server.get_device_type_id_display }}</td>
                            <td class="center">{{ server.get_device_status_id_display }}</td>
                            <td class="center">{{ server.get_is_sync_display }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'vendors/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendors/datatables/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'js/tables.js' %}"></script>
{% endblock %}